package org.argeo.connect.tracker;

/** Centralise constants */
public interface TrackerConstants {
	String TRACKER_DOMAIN_PREFIX = "org.argeo";

	// ISSUE PRIORITY STATUSES
	int TRACKER_PRIORITY_LOWEST = 0;
	int TRACKER_PRIORITY_LOW = 25;
	int TRACKER_PRIORITY_NORMAL = 50;
	int TRACKER_PRIORITY_HIGH = 75;
	int TRACKER_PRIORITY_HIGHEST = 100;

	// ISSUE IMPORTANCE STATUSES
	int TRACKER_IMPORTANCE_ENHANCEMENT = 0;
	int TRACKER_IMPORTANCE_TRIVIAL = 25;
	int TRACKER_IMPORTANCE_MINOR = 50;
	int TRACKER_IMPORTANCE_NORMAL = 75;
	int TRACKER_IMPORTANCE_MAJOR = 100;
	int TRACKER_IMPORTANCE_CRITICAL = 125;
	int TRACKER_IMPORTANCE_BLOCKER = 150;

	// UI CONSTANTS
	int SEARCH_TEXT_DELAY = 800;
}
